# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: MekHQ CI with Gradle

on:
  pull_request:
    branches: [ master ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: mekhq
    - name: Checkout MegaMek
      uses: actions/checkout@v2
      with:
        repository: MegaMek/megamek
        path: megamek
    - name: Checkout MegaMekLab
      uses: actions/checkout@v2
      with:
        repository: MegaMek/megameklab
        path: megameklab
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew (*nix or MacOS)
      working-directory: mekhq  
      run: chmod +x gradlew
    - name: Build with Gradle
      id: gradle_build
      working-directory: mekhq
      run: ./gradlew -I .github/build-scan-init.gradle build --info --stacktrace --scan "-Dscan.link.VCS=${{ github.event.pull_request.html_url }}"
    - name: Upload Test Logs on Failure
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: cd-failure-logs
        path: ./mekhq/MekHQ/build/reports/
    - name: Comment on PR with Build Scan URI
      uses: thollander/actions-comment-pull-request@master
      if: always() && steps.gradle_build.outputs.buildScanUri != ''
      with:
        message: Build scan available at ${{ steps.gradle_build.outputs.buildScanUri }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Releases
      uses: actions/upload-artifact@v2-preview
      with:
        name: releases
        path: ./mekhq/MekHQ/build/distributions/
        
  other_os_ci:
    needs: ci_cd
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew (*nix or MacOS)
      run: chmod +x gradlew
      if: runner.os != 'Windows'
    - name: Build with Gradle
      run: ./gradlew test --stacktrace
    - name: Upload Test Logs on Failure
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ci-failure-logs
        path: MekHQ/build/reports/
